allowed_domains = [
   "tripadvisor.com",
    "travel.usnews.com",
    "travelandleisure.com",
    "bigseventravel.com",
    "timeout.com",
    "scrolltheglobe.com",
    "tourscanner.com",
    "rd.com",
    "thesavvyglobetrotter.com",
    "passportvoyager.com",
    "theblondeabroad.com",
    "nomadicmatt,com",
    "goatsontheroad.com",
    "travelfashiongirl.com",
    "intrepidtravel.com",
    "bucketlistly.blog",
    "myownwaytotravel.com",
    "smartertravel.com",
    "lonelyplanet.com",
    "travelsofadam.com",
    "happytowonder.com",
    "fodors.com",
    "travelnuity.com",
    "travellingwithdiana.com",
    "euronews.com",
    "bemytravelhouse.com",
    "budgetyourtrip.com",
    "barnesandnoble.com",
    "touropia.com",
    "traveltriangle.com",
    "planetware.com",
    "jetsetter.com",
    "roadaffair.com",
    "travelanddestinations.com",
    "thrillophilia.com",
    "yogawinetravel.com",
    "chinadiscovery.com",
    "touropia.com",
    "theculturetrip.com",
    "thecrazytourist.com",
    "nomadicmatt.com",
    "thecutlerychronicles.com",
    "timeout.com",
    "autoeurope.com",
    "globalgrasshopper.com",
    "fullsuitcase.com",
    "go2africa.com"
]

urls = [
    "https://www.touropia.com/best-places-to-visit-in-india/",
    "https://traveltriangle.com/blog/places-to-visit-in-india-before-you-turn-30/",
    "https://www.planetware.com/india/best-places-to-visit-in-india-ind-1-26.htm",
    "https://www.jetsetter.com/magazine/most-beautiful-places-to-visit-in-india/",
    "https://www.roadaffair.com/best-places-to-visit-in-thailand/",
    "https://www.travelanddestinations.com/best-places-to-visit-in-thailand/",
    "https://www.thrillophilia.com/places-to-visit-in-hong-kong",
    "https://www.yogawinetravel.com/unique-things-to-do-in-hong-kong-that-probably-arent-in-your-guidebook/",
    "https://www.chinadiscovery.com/hong-kong/places-to-visit-in-hong-kong.html",
    "https://www.planetware.com/tourist-attractions-/beijing-peking-chn-bj-bj.htm",
    "https://www.travelchinaguide.com/package/beijing/top-10-places-to-visit.htm",
    "https://www.touropia.com/tourist-attractions-in-beijing/",
    "https://theculturetrip.com/europe/germany/articles/20-must-visit-attractions-in-munich/",
    "https://www.thecrazytourist.com/25-best-things-munich-germany/",
    "https://www.nomadicmatt.com/travel-guides/germany-travel-tips/munich/",
    "https://www.thecutlerychronicles.com/25-best-things-in-munich/",
    "https://www.timeout.com/australia/things-to-do/best-places-to-visit-in-australia",
    "https://www.autoeurope.com/travel-blog/top-5-places-to-visit-in-austria/",
    "https://globalgrasshopper.com/destinations/europe/10-beautiful-places-visit-austria/",
    "https://fullsuitcase.com/south-africa-places-to-visit/",
    "https://www.go2africa.com/destinations/south-africa/where-to-go"
    #  "https://www.tripadvisor.com/blog/worlds-most-booked-attractions-2019/",
#      "https://travel.usnews.com/rankings/best-usa-vacations/",
    #  "https://www.timeout.com/los-angeles/things-to-do/los-angeles-attractions"
    #  "https://www.travelandleisure.com/trip-ideas/best-places-to-travel-in-2020",
    #  "https://bigseventravel.com/50-bucket-list-places-2020/",
    #  "https://travel.usnews.com/los_angeles_ca/things_to_do/",
    #  "https://scrolltheglobe.com/15-must-see-places-in-los-angeles/",
    #  "https://www.tripadvisor.com/Attractions-g60713-Activities-San_Francisco_California.html",
    #  "https://tourscanner.com/blog/things-to-do-san-francisco/",
    #  "https://travel.usnews.com/rankings/best-usa-vacations/",
    #  "https://www.rd.com/article/the-ultimate-american-road-trip-guide/",
    #  "https://www.thesavvyglobetrotter.com/usa-travel-bucket-list/",
    #  "https://www.passportvoyager.com/ultimate-usa-travel-bucket-list/",
    #  "https://www.theblondeabroad.com/ultimate-europe-travel-guide/",
    #  "https://www.nomadicmatt.com/travel-guides/europe-travel-tips/",
    #  "https://www.goatsontheroad.com/backpacking-europe/",
    #  "https://www.travelfashiongirl.com/europe-in-spring/",
    #  "http://www.intrepidtravel.com/adventures/eastern-europe-one-week-guide/",
    #  "https://www.bucketlistly.blog/posts/3-months-itinerary-europe",
    #  "https://myownwaytotravel.com/budget-travel-europe-ultimate-guide/",
    #  "https://www.smartertravel.com/planning-trip-europe-10-step-guide/",
    #  "https://www.lonelyplanet.com/europe",
    #  "https://travelsofadam.com/europe/",
    #  "https://happytowander.com/cheapest-way-to-travel-europe/",
    #  "https://www.fodors.com/world/europe/france/paris/experiences/news/the-ultimate-guide-to-spending-an-evening-in-paris-from-your-home",
    #  "https://www.travelnuity.com/travelling-in-europe-with-a-dog/",
    #  "https://www.travellingwithdiana.com/paris-travel-guide/",
    #  "https://www.euronews.com/travel/2021/04/09/a-guide-to-europe-s-worst-tourist-attractions",
    #  "https://www.bemytravelmuse.com/what-to-do-in-berlin/",
    #  "https://www.budgetyourtrip.com/italy-guide/ultimate-amalfi-coast-travel-guide/80/",
    #  "https://www.barnesandnoble.com/w/the-ultimate-europe-train-travel-guide-a-bluemarbleexpress-explore-the-world-vacation-series-j-doyle-white/1119131516",
]
